node('docker') {
 
    stage ('Checkout')
	{
        checkout scm
	}
    stage ('Build & UnitTest')
	 {
        sh "docker build -t simpleloginapp:B${BUILD_NUMBER} -f SimpleLogin/Dockerfile ."
        sh "docker build -t simpleloginapp:test-B${BUILD_NUMBER} -f SimpleLogin/Dockerfile.Integration ."
     }
	stage ('Pusblish UT Reports'){
        containerID = sh (
            script: "docker run -d simpleloginapp:B${BUILD_NUMBER}", 
        returnStdout: true
        ).trim()
        echo "Container ID is ==> ${containerID}"
        sh "docker cp ${containerID}:/TestResults/test_results.xml test_results.xml"
        sh "docker stop ${containerID}"
        sh "docker rm ${containerID}"
        step([$class: 'MSTestPublisher', failOnError: false, testResultsFile: 'test_results.xml'])    
	}
    stage ('Integration Test')
	{
        sh "docker-compose -f SimpleLogin/docker-compose.integration.yml up --force-recreate --abort-on-container-exit"
       	}
}
